{% set name = "oyaml" %}
{% set version = "0.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: de52d8ef5dc91c65376bfc0ef6c8bf98c1bb1c4387e3d46b7fff5a946954c993

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pyyaml

test:
  imports:
    - oyaml

about:
  home: https://github.com/wimglenn/oyaml
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Ordered YAML: drop-in replacement for PyYAML which preserves dict ordering"

extra:
  recipe-maintainers: 
    - bebatut
