{% set name = "oyaml" %}
{% set version = "0.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03990464021274031c2905c3ee5c1345f318b30d0f247ea4368c44921e2b1d67

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pyyaml

test:
  imports:
    - oyaml

about:
  home: https://github.com/wimglenn/oyaml
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Ordered YAML: drop-in replacement for PyYAML which preserves dict ordering"

extra:
  recipe-maintainers: 
    - bebatut
    - quartox
