travis:
  secure:
    BINSTAR_TOKEN: FwLhaagGLDbrJ8QxHVnbHXbje9R4X0/prUlgsJx6GWKzCBdsqG8nW98wiX2Sw5F4UWz0pVd6iZG+mqrzkdNI+0tefRSQjK5fTXa3MVgvME9RTUyV6nO8LvycqVNUn47yQIsatkY/bIHsSmFvkzkG8L/cgtquPT4nYjte1snhwUSj0zDp2UzH+2+2rALukcMjcP4l85Qx5hJHiTWzsUoktJGr0i0xDXP0dFPJpTA//s33ZItPs84PCcsH3eQhaqNiSZv+DHue6cDashODKCK1zLBd53ptjWffIEtuZFmo56usidNI/B5VmB4F3M17+zouDLkb8N7FnxYv/3P9NkrOvijS8g15P2/plzwsAfEWgDjBNXTZlkbVPev3MKDM7mGWSG5+BuCmujhNnUFvgPf1OQI1rtd4IEZLVoWCQ5G7ewLI7k94hiEm5LqwwFeXcWInajgXz1GMmZOCKdsGDtAmrWc7KzqyC1lNclsXR6y0Sa4sF9nYG2L4aqZgGmSD7bWquT6wHF93t9JeRvR9p/Ua2YcH3qXUk0IKb+mwPc6C4ik6ZRjlKWv4cAiSTvtAVnXW8rIFiH9hxxhXd5nHXbajQ2vVEHbbrbem5ih064xVBOZGDSY/O9XPqb4kLAvXNOjHJcKx5uNHgzbQ3r02w6Tw+qwWFK0IsykyOA1tkpRmEjQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
